### 사용자 등록
POST http://localhost:8080/v1/member/signUp
Content-Type: application/json;charset=utf-8

{
  "email": "kslbsh@gmail.com",
  "password": "1234"
}


### 사용자 로그인
POST http://localhost:8080/v1/member/signIn
Content-Type: application/json

{
  "email": "kslbsh@gmail.com",
  "password": "1234"
}


### 사용자 로그인
GET http://localhost:8080/v1/member/me
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoicHJncm1zIiwiaWQiOjEsImV4cCI6MTY1ODU4NTA5NCwiaWF0IjoxNjU4NTg0NzM0LCJlbWFpbCI6ImtzbGJzaEBnbWFpbC5jb20ifQ.do_j7YZq-NFuBnD6hNqMpQiy-MXjgJNeKqgVjvgY6nr--44XDbNHlFOHcZVgluFpn5Alkm4KEp3s-dJ868286Q


