spring:
  jpa:
    open-in-view: false

  main:
    allow-circular-references: true

  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema_new.sql
      #      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8
  h2:
    console:
      enabled: true
      settings:
        trace: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test_mem;DB_CLOSE_ON_EXIT=FALSE
  jackson:
    default-property-inclusion: non_null

jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 360


logging:
  level:
    com.example: debug
    org.springframework.security: debug
